[versions]
accompanist = "0.34.0"
activity = "1.9.1"
androidGradle = "8.5.2"
androidXCore = "1.13.1"
androidXNavigation = "2.7.7"
androidxHiltCompiler = "1.2.0"
androidxTestCore = "1.6.1"
annotation = "1.8.1"
appcompat = "1.7.0"
biometric = "1.2.0-alpha05"
brotli = "0.1.2"
browser = "1.8.0"
bugsnag = "8.1.0"
bugsnagAndroid = "6.6.1"
coilCompose = "2.7.0"
colorpickerview = "2.3.0"
composableTable = "1.2.0"
composeBom = "2024.06.00"
composeCodeEditor = "2.0.3"  # Updating breaks a lot of things, this will require some work, or possibly a different library
conscrypt = "2.5.2"
coreSplashscreen = "1.0.1"
desugar = "2.0.4"
exifinterface = "1.3.7"
googleShortcuts = "1.1.0"
gson = "2.11.0"
hilt = "2.51.1"
hiltNavigationCompose = "1.2.0"
hiltWork = "1.2.0"
jbcrypt = "0.4"
jsoup = "1.18.1"
kotlin = "2.0.0"
kotlinxCoroutines = "1.8.1"
ksp = "2.0.0-1.0.22"
lifecycle = "2.7.0"
liquidcore = "0.6.2"  # This is not the latest version, but it's the latest one that has a published artifact, and the newer ones lead to a larger build size without adding significant benefits, so I'm keeping this at the old version for now
markdown = "0.7.0"
material3 = "1.2.1"
mockk = "1.13.12"
okhttp3 = "5.0.0-alpha.11"  # Do not update to 5.0.0-alpha.12, it breaks when minified
okhttpDigest = "3.1.0"
paho = "1.2.5"
peko = "2.2.0"
persistentCookieJar = "v1.0.1"
playServicesLocation = "21.3.0"
preference = "1.2.1"
realm = "2.0.0"  # only update if it's really necessary, this thing grows larger with every version...
reorderable = "2.3.0"
spotless = "6.4.2"
taskerplugin = "0.4.10"
ucrop = "2.2.8"
unmockplugin = "0.7.9"
workRuntime = "2.9.0"
zoomable = "1.6.1"

[libraries]
accompanist-systemuicontroller = { module = "com.google.accompanist:accompanist-systemuicontroller", version.ref = "accompanist" }
android-gradle = { module = "com.android.tools.build:gradle", version.ref = "androidGradle" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activity" }
androidx-annotation = { module = "androidx.annotation:annotation", version.ref = "annotation" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
androidx-biometric = { module = "androidx.biometric:biometric", version.ref = "biometric" }
androidx-browser = { module = "androidx.browser:browser", version.ref = "browser" }
androidx-compose-bom = { module = "androidx.compose:compose-bom", version.ref = "composeBom" }
androidx-compose-material3 = { module = "androidx.compose.material3:material3", version.ref = "material3" }
androidx-compose-materialIconsExtended = { module = "androidx.compose.material:material-icons-extended" }
androidx-compose-uiTooling = { module = "androidx.compose.ui:ui-tooling" }
androidx-compose-uiToolingPreview = { module = "androidx.compose.ui:ui-tooling-preview" }
androidx-core = { module = "androidx.core:core-ktx", version.ref = "androidXCore" }
androidx-exifinterface = { module = "androidx.exifinterface:exifinterface", version.ref = "exifinterface" }
androidx-googleShortcuts = { module = "androidx.core:core-google-shortcuts", version.ref = "googleShortcuts" }
androidx-hilt-compiler = { module = "androidx.hilt:hilt-compiler", version.ref = "androidxHiltCompiler" }
androidx-hilt-work = { module = "androidx.hilt:hilt-work", version.ref = "hiltWork" }
androidx-lifecycle-runtime-compose = { module = "androidx.lifecycle:lifecycle-runtime-compose", version.ref = "lifecycle" }
androidx-lifecycle-viewmodel = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "lifecycle" }
androidx-lifecycle-viewmodel-compose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "lifecycle" }
androidx-navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "androidXNavigation" }
androidx-preference = { module = "androidx.preference:preference-ktx", version.ref = "preference" }
androidx-splashscreen = { module = "androidx.core:core-splashscreen", version.ref = "coreSplashscreen" }
androidx-test = { module = "androidx.test:core-ktx", version.ref = "androidxTestCore" }
androidx-work-runtime = { module = "androidx.work:work-runtime-ktx", version.ref = "workRuntime" }
brotli = { module = "org.brotli:dec", version.ref = "brotli" }
bugsnag-android = { module = "com.bugsnag:bugsnag-android", version.ref = "bugsnagAndroid" }
bugsnag-gradle = { module = "com.bugsnag:bugsnag-android-gradle-plugin", version.ref = "bugsnag" }
coil-compose = { module = "io.coil-kt:coil-compose", version.ref = "coilCompose" }
colorpickerview = { module = "com.github.skydoves:colorpickerview", version.ref = "colorpickerview" }
composableTable = { module = "io.github.sunny-chung:composable-table", version.ref = "composableTable" }
composeCodeEditor = { module = "com.github.qawaz:compose-code-editor", version.ref = "composeCodeEditor" }
conscrypt = { module = "org.conscrypt:conscrypt-android", version.ref = "conscrypt" }
desugar = { module = "com.android.tools:desugar_jdk_libs", version.ref = "desugar" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hilt" }
hilt-android-compiler = { module = "com.google.dagger:hilt-android-compiler", version.ref = "hilt" }
hilt-navigation-compose = { module = "androidx.hilt:hilt-navigation-compose", version.ref = "hiltNavigationCompose" }
jbcrypt = { module = "org.mindrot:jbcrypt", version.ref = "jbcrypt" }
jetbrains-markdown = { module = "org.jetbrains:markdown", version.ref = "markdown" }
jsoup = { module = "org.jsoup:jsoup", version.ref = "jsoup" }
kotlin-gradle-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "kotlin" }
kotlin-test-junit5 = { module = "org.jetbrains.kotlin:kotlin-test-junit5", version.ref = "kotlin" }
kotlinx-coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinxCoroutines" }
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlinxCoroutines" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinxCoroutines" }
liquidcore = { module = "com.github.LiquidPlayer:LiquidCore", version.ref = "liquidcore" }
mockk = { module = "io.mockk:mockk", version.ref = "mockk" }
okhttp3 = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp3" }
okhttpDigest = { module = "io.github.rburgst:okhttp-digest", version.ref = "okhttpDigest" }
paho-mqtt = { module = "org.eclipse.paho:org.eclipse.paho.client.mqttv3", version.ref = "paho" }
peko = { module = "com.markodevcic:peko", version.ref = "peko" }
persistentCookieJar = { module = "com.github.franmontiel:PersistentCookieJar", version.ref = "persistentCookieJar" }
playServices-location = { module = "com.google.android.gms:play-services-location", version.ref = "playServicesLocation" }
realm = { module = "io.realm.kotlin:library-base", version.ref = "realm" }
reorderable = { module = "sh.calvin.reorderable:reorderable", version.ref = "reorderable" }
taskerplugin = { module = "com.joaomgcd:taskerpluginlibrary", version.ref = "taskerplugin" }
ucrop = { module = "com.github.yalantis:ucrop", version.ref = "ucrop" }
unmock = { module = "com.github.bjoernq:unmockplugin", version.ref = "unmockplugin" }
zoomable = { module = "net.engawapg.lib:zoomable", version.ref = "zoomable" }

[plugins]
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
hiltAndroid = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
kotlinJvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
realm = { id = "io.realm.kotlin", version.ref = "realm" }
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }